### ISSUE TITLE
Please release Swift 3 support

### ISSUE THREAD

**Issue by stevenp** [Jakenberg/ObjectMapper-Realm#6]
It appears as though these changes are ready to go and the podspec just needs to be updated. Would you mind doing this?

**Comment by 0xjmp** [comment]
Hi @stevenp! I just released `0.2` which has swift 3 support. Enjoy! 🌠

**Comment by alizainprasla** [comment]
![screen shot 2018-01-06 at 9 39 35 pm](https://user-images.githubusercontent.com/820419/34641715-311cb456-f32a-11e7-914f-1ef502b22461.png)

What am I doing wrong? Using swift 3.2

**Comment by 0xjmp** [comment]
@alizainprasla sorry to hear you're having trouble.

I'd suggest doing two things:

1. Update your `Podfile` so that version spec is rough: `pod 'ObjectMapper+Realm', '~> 0.2'` (latest is `0.5` as of this writing).
2. Confirm your `Podfile.lock` isn't still using an older version of `ObjectMapper+Realm` by running: `pod update ObjectMapper+Realm`.

I started a scratch project in the same version of Xcode just now, and was able to get all setup okay...
